/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation
 *
 * The sidebars can be generated from the filesystem, or explicitly defined here.
 *
 * Create as many sidebars as you want.
 */

const DOCS_URL = process.env.DOCS_URL || 'https://docs.epilot.io'

const PRICING_PLAYGROUND_URL = `${DOCS_URL}/pricing-playground/index.html`

module.exports = {
  docsSidebar: [
    'intro',
    {
      type: 'category',
      label: 'Agent Toolkit',
      collapsible: true,
      collapsed: true,
      items: [
        'agent-toolkit/overview',
        'agent-toolkit/setup',
        'agent-toolkit/mcp-server',
      ],
    },
    {
      type: 'category',
      label: 'Architecture',
      collapsible: true,
      collapsed: true,
      items: [
        { type: 'autogenerated', dirName: 'architecture' },
        { type: 'autogenerated', dirName: 'ai' },
        { type: 'autogenerated', dirName: 'datalake' },
        'audit-logs',
      ],
    },
    {
      type: 'category',
      label: 'Auth & Security',
      collapsible: true,
      collapsed: true,
      items: [
        { type: 'autogenerated', dirName: 'auth' },
        { type: 'autogenerated', dirName: 'sso' },
        { type: 'autogenerated', dirName: 'environments' },
      ],
    },
    {
      type: 'category',
      label: 'SDK',
      collapsible: true,
      collapsed: true,
      items: [{ type: 'autogenerated', dirName: 'sdk' }],
    },
    {
      type: 'category',
      label: 'Entities',
      collapsible: true,
      collapsed: true,
      items: [
        { type: 'autogenerated', dirName: 'entities' },
        { type: 'autogenerated', dirName: 'files' },
        { type: 'autogenerated', dirName: 'collaboration' },
      ],
    },
    {
      type: 'category',
      label: 'Journeys',
      collapsible: true,
      collapsed: true,
      items: [
        { type: 'autogenerated', dirName: 'journeys' },
        { type: 'autogenerated', dirName: 'ui-design' },
      ],
    },
    {
      type: 'category',
      label: 'Data Governance',
      collapsible: true,
      collapsed: true,
      items: [{ type: 'autogenerated', dirName: 'data-governance' }],
    },
    {
      type: 'category',
      label: 'Communications',
      collapsible: true,
      collapsed: true,
      items: [{ type: 'autogenerated', dirName: 'messaging' }],
    },
    {
      type: 'category',
      label: 'Notes',
      collapsible: true,
      collapsed: true,
      items: [{ type: 'autogenerated', dirName: 'notes' }],
    },
    {
      type: 'category',
      label: 'Templates',
      collapsible: true,
      collapsed: true,
      items: [{ type: 'autogenerated', dirName: 'templates' }],
    },
    {
      type: 'category',
      label: 'Portals',
      collapsible: true,
      collapsed: true,
      items: [{ type: 'autogenerated', dirName: 'portals' }],
    },
    {
      type: 'category',
      label: 'Automation',
      collapsible: true,
      collapsed: true,
      items: [{ type: 'autogenerated', dirName: 'automation' }],
    },
    {
      type: 'category',
      label: 'Workflows',
      collapsible: true,
      collapsed: true,
      items: [{ type: 'autogenerated', dirName: 'workflows' }],
    },
    {
      type: 'category',
      label: 'Blueprints',
      collapsible: true,
      collapsed: true,
      items: [{ type: 'autogenerated', dirName: 'blueprints' }],
    },
    {
      type: 'category',
      label: 'Pricing',
      collapsible: true,
      collapsed: true,
      items: [
        'pricing/README',
        {
          type: 'category',
          label: 'Pricing Library',
          items: [
            { type: 'autogenerated', dirName: 'pricing/pricing-library' },
          ],
        },
        {
          type: 'link',
          label: 'Pricing Playground',
          href: PRICING_PLAYGROUND_URL,
        },
        'pricing/entities',
        'pricing/catalog',
        'pricing/orders',
        'pricing/ecommerce',
        'pricing/pricing-models',
        { type: 'autogenerated', dirName: 'deadlines' },
      ],
    },
    {
      type: 'category',
      label: 'Integrations',
      collapsible: true,
      collapsed: true,
      items: [{ type: 'autogenerated', dirName: 'integrations' }],
    },
    {
      type: 'category',
      label: 'CLI',
      collapsible: true,
      collapsed: true,
      items: [{ type: 'autogenerated', dirName: 'cli' }],
    },
  ],

  // Dedicated sidebar for the Apps section (reached via the "Apps" navbar item).
  appsSidebar: [
    'apps/overview',
    {
      type: 'category',
      label: 'Getting started',
      collapsible: true,
      collapsed: false,
      items: [
        'apps/getting-started/quick-start',
        'apps/getting-started/developer-sandbox',
        'apps/getting-started/private-vs-public',
      ],
    },
    {
      type: 'category',
      label: 'Build',
      collapsible: true,
      collapsed: false,
      items: [
        'apps/app-manifest',
        {
          type: 'category',
          label: 'Components',
          collapsible: true,
          collapsed: true,
          link: { type: 'doc', id: 'apps/components/overview' },
          items: [
            'apps/components/custom-journey-block',
            'apps/components/custom-page',
            'apps/components/portal-extension',
            'apps/components/external-product-catalog',
            'apps/components/custom-action',
            'apps/components/api-proxy',
          ],
        },
        {
          type: 'category',
          label: 'Functions',
          collapsible: true,
          collapsed: true,
          link: { type: 'doc', id: 'apps/functions/overview' },
          items: [
            'apps/functions/writing-functions',
            'apps/functions/workflow-functions',
            'apps/functions/scheduled-functions',
            'apps/functions/deploy-and-update',
          ],
        },
        'apps/app-surfaces',
        'apps/configure-permissions',
        'apps/app-options',
      ],
    },
    {
      type: 'category',
      label: 'Develop & deploy',
      collapsible: true,
      collapsed: false,
      items: ['apps/cli', 'apps/development-mode', 'apps/versioning'],
    },
    {
      type: 'category',
      label: 'Publish',
      collapsible: true,
      collapsed: false,
      items: [
        'apps/publishing/verification-process',
        'apps/publishing/requirements',
      ],
    },
    {
      type: 'category',
      label: 'Guides',
      collapsible: true,
      collapsed: false,
      items: [
        {
          type: 'doc',
          id: 'apps/how-to-guides/build-a-custom-jb',
          label: 'Build a custom journey block',
        },
      ],
    },
  ],
}
