/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation
 *
 * The sidebars can be generated from the filesystem, or explicitly defined here.
 *
 * Create as many sidebars as you want.
 */

const DOCS_URL = process.env.DOCS_URL || 'https://docs.epilot.io';

const PLAYGROUND_URL = `${DOCS_URL}/pricing-playground/index.html`;

module.exports = {
  docsSidebar: [
    'intro',
    {
      type: 'category',
      label: 'Architecture',
      collapsible: true,
      collapsed: true,
      items: [
        { type: 'autogenerated', dirName: 'architecture' },
        { type: 'autogenerated', dirName: 'ai' },
        { type: 'autogenerated', dirName: 'datalake' },
        'audit-logs',
      ],
    },
    {
      type: 'category',
      label: 'Auth & Security',
      collapsible: true,
      collapsed: true,
      items: [
        { type: 'autogenerated', dirName: 'auth' },
        { type: 'autogenerated', dirName: 'sso' },
      ],
    },
    {
      type: 'category',
      label: 'SDK',
      collapsible: true,
      collapsed: true,
      items: [{ type: 'autogenerated', dirName: 'sdk' }],
    },
    {
      type: 'category',
      label: 'Entities',
      collapsible: true,
      collapsed: true,
      items: [
        { type: 'autogenerated', dirName: 'entities' },
        { type: 'autogenerated', dirName: 'files' },
        { type: 'autogenerated', dirName: 'collaboration' },
      ],
    },
    {
      type: 'category',
      label: 'Journeys',
      collapsible: true,
      collapsed: true,
      items: [
        { type: 'autogenerated', dirName: 'journeys' },
        { type: 'autogenerated', dirName: 'ui-design' },
      ],
    },
    {
      type: 'category',
      label: 'Messaging',
      collapsible: true,
      collapsed: true,
      items: [{ type: 'autogenerated', dirName: 'messaging' }],
    },
    {
      type: 'category',
      label: 'Notes',
      collapsible: true,
      collapsed: true,
      items: [{ type: 'autogenerated', dirName: 'notes' }],
    },
    {
      type: 'category',
      label: 'Templates',
      collapsible: true,
      collapsed: true,
      items: [{ type: 'autogenerated', dirName: 'templates' }],
    },
    {
      type: 'category',
      label: 'Portals',
      collapsible: true,
      collapsed: true,
      items: [{ type: 'autogenerated', dirName: 'portals' }],
    },
    {
      type: 'category',
      label: 'Automation',
      collapsible: true,
      collapsed: true,
      items: [{ type: 'autogenerated', dirName: 'automation' }],
    },
    {
      type: 'category',
      label: 'Workflows',
      collapsible: true,
      collapsed: true,
      items: [{ type: 'autogenerated', dirName: 'workflows' }],
    },
    {
      type: 'category',
      label: 'Blueprints',
      collapsible: true,
      collapsed: true,
      items: [{ type: 'autogenerated', dirName: 'blueprints' }],
    },
    {
      type: 'category',
      label: 'Pricing',
      collapsible: true,
      collapsed: true,
      items: [
        'pricing/README',
        {
          type: 'category',
          label: 'Pricing Library',
          items: [{ type: 'autogenerated', dirName: 'pricing/pricing-library' }],
        },
        {
          type: 'link',
          label: 'Pricing Playground',
          href: PLAYGROUND_URL,
        },
        'pricing/entities',
        'pricing/catalog',
        'pricing/orders',
        'pricing/ecommerce',
        'pricing/pricing-models',
        { type: 'autogenerated', dirName: 'deadlines' },
      ],
    },
    {
      type: 'category',
      label: 'Integrations',
      collapsible: true,
      collapsed: true,
      items: [{ type: 'autogenerated', dirName: 'integrations' }],
    },
    {
      type: 'category',
      label: 'CLI',
      collapsible: true,
      collapsed: true,
      items: [{ type: 'autogenerated', dirName: 'cli' }],
    },
    {
      type: 'category',
      label: 'Apps',
      collapsible: true,
      collapsed: true,
      items: [{ type: 'autogenerated', dirName: 'apps' }],
    },
  ],
};
